### ISSUE TITLE
Alternative to hcat(n...)

### ISSUE THREAD

**Issue by rapus95** [mewfree/advent-of-meow-2021#1]
Hey, I stumbled across your article https://www.damiengonot.com/blog/julia-learnings-aoc-2021 (side note, your "contact me" links are dead as they point to file://about) and you asked to contact you, if there was an alternative to convert an array of arrays to a matrix. There is now, since Julia 1.9 (~May 2023), it's called [`stack`](https://docs.julialang.org/en/v1/base/arrays/#Base.stack). I only learned about that myself 2 days ago while looking into code golfing solutions in Julia for this year :D (In particular, [that](https://www.reddit.com/r/adventofcode/comments/1h689qf/comment/m0e6cee/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) solution)

While I see, you've been using ruby for 2 years now, I still wanted to reach out to you.
Happy Advent of Code/Meowing!

**Comment by mewfree** [comment]
Thank you so much for reaching out @rapus95!

I have fixed the contact me / `/about` links on my [personal-website](https://github.com/mewfree/personal-website), thank you for pointing it out.

I'm so glad `stack` exists now! I need to keep up with Julia's recent updates / features. Because I mostly write Ruby and TypeScript at my job now, I've been using Ruby for simplicity but I'm still interested in Julia, it's a very elegant language. Maybe I should do some of the Advent of Code challenges in Julia again 🙂.

Good luck with Advent of Code and thanks again for letting me know about `stack`, I really appreciate it.

**Comment by mewfree** [comment]
Thank you so much for reaching out @rapus95!

I have fixed the contact me / `/about` links on my [personal-website](https://github.com/mewfree/personal-website), thank you for pointing it out.

I'm so glad `stack` exists now! I need to keep up with Julia's recent updates / features. Because I mostly write Ruby and TypeScript at my job now, I've been using Ruby for simplicity but I'm still interested in Julia, it's a very elegant language. Maybe I should do some of the Advent of Code challenges in Julia again 🙂.

Good luck with Advent of Code and thanks again for letting me know about `stack`, I really appreciate it.

**Comment by mewfree** [comment]
If you ever need to contact me again, you can head over to https://www.damiengonot.com/about for my email

Cheers
